### ISSUE TITLE
[Question] Toggle Key Binding

### ISSUE THREAD

**Issue by idr4n** [NeoVintageous/NeoVintageousToggle#2]
Hi,

This command is awesome. So far I have been able to use it only from the command palette, and tried assigning a key binding to it, but it didn't work. Something like

```
  { "keys": ["ctrl+alt+super+t"], "command": "Toggle NeoVintageous" }
```

Is this possible at all?

**Comment by gerardroche** [comment]
There is no default key binding; add your preferred mapping: `Menu > Preferences > Key Bindings`


```json
[
    { "keys": ["ctrl+alt+shift+t"], "command": "toggle_neovintageous" }
]
```

**Comment by idr4n** [comment]
Great, thanks! Works perfectly.
